analyzer:
  strong-mode:
    implicit-dynamic: false

  errors:
    always_use_package_imports: error
    annotate_overrides: error
    avoid_empty_else: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: error
    avoid_returning_null_for_void: error
    avoid_return_types_on_setters: error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: error
    empty_catches: error
    empty_statements: error
    exhaustive_cases: error
    iterable_contains_unrelated_type: error
    library_names: error
    library_prefixes: error
    list_remove_unrelated_type: error
    missing_required_param: error
    missing_return: error
    non_constant_identifier_names: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    prefer_final_fields: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_contains: error
    prefer_void_to_null: error
    recursive_getters: error
    todo: ignore
    unawaited_futures: error
    unnecessary_lambdas: error
    unnecessary_late: error
    unnecessary_new: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unrelated_type_equality_checks: error
    use_rethrow_when_possible: error
    void_checks: error

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - await_only_futures
    - avoid_returning_null_for_void
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - avoid_web_libraries_in_flutter
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - non_constant_identifier_names
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - only_throw_errors
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks