name: lifestylediet
description: Keep up with our diet
publish_to: none
version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.2

dependencies:
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  provider: 6.0.5
  shared_preferences: 2.1.1
  equatable: 2.0.5
  meta: 1.9.1
  animated_widgets: 1.1.0
  firebase_core: 2.13.0
  cloud_firestore: 4.7.1
  firebase_auth: 4.6.1
  openfoodfacts: 2.5.1
  uuid: 3.0.7
  charts_flutter: 0.12.0
  flutter_barcode_scanner: 2.0.0
  image_picker: 0.8.7+5
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  bloc_test: 9.1.2
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
