name: lifestylediet
description: Keep up with our diet
publish_to: none
version: 1.1.0

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.7.5

dependencies:
  bloc: 8.1.1
  flutter_bloc: 8.1.2
  provider: 6.0.5
  shared_preferences: 2.0.18
  equatable: 2.0.5
  meta: 1.9.0
  animated_widgets: 1.1.0
  firebase_core: 2.7.0
  cloud_firestore: 4.4.3
  firebase_auth: 4.2.9
  openfoodfacts: 2.3.1
  uuid: 3.0.7
  charts_flutter: 0.12.0
  google_fonts: 4.0.3
  flutter_barcode_scanner: 2.0.0
  image_picker: 0.8.6+4
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  bloc_test: 9.1.1
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
